name: Dev Environment CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: build and push docker image to ghcr
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          # username: ${{ github.actor }}
          username: surattinon
          # password: ${{secrets.GITHUB_TOKEN}}
          password: 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
          logout: true

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          tags: |
            ghcr.io/surattinon/ubuntulab:${{ env.GITHUB_SHA }}
          build-args: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
